# Formato: "Nombre": (Gramos_CHO, "Unidad_Medida")
# Ajustado a estándar: 1 taza = 250 ml | 1/2 taza = 125 ml (Factor x1.25 en tazas)
ALIMENTOS_POR_GRUPO = {
    "🍉 Frutas": {
        "Plátano": (15.0, "1/2 unidad"),
        "Naranja": (15.0, "1 unidad regular"),
        "Manzana": (15.0, "1 unidad pequeña"),
        "Frutillas": (18.75, "1 taza"),
        "Mora": (18.75, "1/2 taza"),
        "Sandia": (18.75, "1 taza"),
        "Melón": (18.75, "1 taza"),
        "Durazno": (15.0, "1 unidad pequeña"),
        "Cerezas": (15.0, "15 unidades"),
        "Chirimoya": (11.0, "1/4 de unidad"),
        "Pera": (15.0, "1 unidad pequeña"),
        "Piña": (18.75, "3/4 de taza"),
        "Kiwi": (15.0, "2 unidades pequeñas"),
        "Frambuesa": (18.75, "1 taza"),
        "Ciruelas": (15.0, "3 unidades"),
        "Uvas": (15.0, "10 unidades"),
        "Pasas": (16.0, "20 unidades"),
        "Huesillo": (15.0, "2 unidades")
    },
    "🌾 Cereales, Papas y Leguminosas": {
        "Arroz": (37.5, "3/4 taza"),
        "Arroz integral": (37.5, "3/4 taza"),
        "Fideos": (37.5, "3/4 taza"),
        "Cabritas": (37.5, "1 1/2 taza"),
        "Mote": (37.5, "3/4 taza"),
        "Pan marraqueta/hallulla": (30.0, "1/2 unidad"),
        "Pan de molde": (30.0, "3 rebanadas"),
        "Pan de molde integral": (23.0, "2 rebanadas"),
        "Pan de high-low": (11.9, "2 rebanadas"),
        "Galletas integrales": (20.0, "6 unidades"),
        "Pan amasado": (30.0, "1/4 unidad"),
        "Galletas de agua": (30.0, "8 unidades"),
        "Galletas champaña": (30.0, "5 unidades"),
        "Arvejas": (37.5, "1 1/2 taza"),
        "Camote": (37.5, "1/2 taza"),
        "Choclo": (50.0, "1 taza"),
        "Habas": (37.5, "1 taza"),
        "Papa": (30.0, "1 unidad regular"),
        "Porotos granados": (31.25, "3/4 taza"),
        "Avena": (37.5, "1/2 taza"),
        "Avena Integral": (17.2, "2 cucharadas"),
        "Avena Instantánea": (20.0, "2 cucharadas"),
        "Chuño": (32.0, "4 cucharadas"),
        "Harina Tostada": (30.0, "4 cucharadas"),
        "Maicena": (30.0, "3 cucharadas"),
        "Quinoa": (25.0, "4 cucharadas"),
        "Sémola": (30.0, "3 cucharadas"),
        "Mermelada Regimel": (0.9, "1 cucharada")
    },
    "🥦 Verduras": {
        "Acelga cocida": (6.25, "1/2 taza"),
        "Alcachofa": (6.0, "1 unidad pequeña"),
        "Beterraga": (6.25, "1/2 taza"),
        "Berenjena": (8.75, "1 1/2 taza"),
        "Brócoli": (6.25, "1 taza"),
        "Champiñones": (6.25, "3/4 taza"),
        "Coliflor": (6.25, "1 taza"),
        "Espárrago": (5.0, "5 unidades"),
        "Porotos verdes": (7.5, "3/4 taza"),
        "Espinaca": (6.25, "1/2 taza"),
        "Salsa de tomate": (6.0, "2 cucharadas"),
        "Zanahoria": (6.25, "1 taza"),
        "Zapallo italiano": (7.5, "1 taza"),
        "Zapallo": (6.25, "1/2 taza"),
        "Ajo": (3.0, "8 dientes"),
        "Apio": (3.75, "1 taza"),
        "Cochayuyo": (3.0, "2 ramas"),
        "Lechuga": (2.5, "1 taza"),
        "Pepino": (3.75, "1 taza"),
        "Pimentón": (5.0, "1/2 taza"),
        "Repollo": (3.75, "1 taza")
    },
    "🥛 Lácteos": {
        "Leche descremada Colun": (11.75, "1 taza 250 ml"),
        "Leche entera": (11.75, "1 taza 250 ml"),
        "Yogurt Oikos": (9.8, "1 unidad"),
        "Yogurt": (10.0, "1 unidad"),
        "Quesillo Colun": (1.4, "1 rebanada 3 cm"),
        "Huevos": (0.6, "1 unidad"),
    },
     "Fiambres": {
        "Pechuga de pollo": (0.1, "1 rebanada"),
        "Pechuga de pavo": (0.2, "1 rebanada")
    }
}